### ISSUE TITLE
Sounds!!

### ISSUE THREAD

**Issue by RickieES** [RickieES/GCPractica1#8]
We haven't added any sounds yet to the game.

Here there are some kind of game sound effects:

https://mixkit.co/free-sound-effects/game/ (mostly retro)
https://www.zapsplat.com/sound-effect-category/game-sounds/
https://opengameart.org/content/library-of-game-sounds

**Comment by alejleal** [comment]
Commit [4cad166](https://github.com/RickieES/GCPractica1/commit/4cad166981157c45201d56aae6f98648f5e422c3) completes this
